### ISSUE TITLE
关于损失函数

### ISSUE THREAD

**Issue by harunakai** [Linfeng-Tang/DRMF#2]
您好，我最近在阅读您的这项工作，但是在代码中发现了论文中似乎并未出现的损失项，您能解释一下这部分的作用吗？如果这部分出现在论文中了，那么这部分对应的是哪项损失函数呢？
具体的位置是[https://github.com/Linfeng-Tang/DRMF/blob/main/utils/losses.py](url)中第98行的第一个加号后部分与第99行的损失，以及他们的超参数为什么这么设置？

**Comment by Linfeng-Tang** [comment]
第98行在式（11）的基础上额外增加了一下基于mask的强度损失 其作用在于约束融合结果在显著目标区域与红外保持一致 而在背景区域与可见光保持一致呢。
第99行是一项用于约束色彩保真的颜色一致性损失。

**Comment by harunakai** [comment]
感谢您的解释！
